source 'https://rubygems.org'

# Specify your gem's dependencies in sbpayment.gemspec
gemspec path: File.expand_path('../../..', __FILE__)

gem 'faraday', '0.16.2'

gem 'pry-byebug'
gem 'webdrivers' unless ENV.key?('CIRCLECI')
